version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - airflow_app-network

  python-data:
    build: ./container-data
    container_name: python-data
    depends_on:
      - mongodb
    networks:
      - airflow_app-network

  python-timelapse:
    build: ./container-timelapse
    container_name: python-timelapse
    depends_on:
      - mongodb
    volumes:
      - shared_volume:/app/shared
    networks:
      - airflow_app-network
  
  php-app:
    build: ./php-mongodb-app
    container_name: app-web
    depends_on:
      - mongodb
    networks:
      - airflow_app-network
    volumes:
      - shared_volume:/var/www/html/shared
    ports:
      - "85:85"

  selenium-chrome:
    image: selenium/standalone-chrome:131.0-chromedriver-131.0
    container_name: selenium-chrome
    networks:
      - airflow_app-network
  
  python-image-api:
    build: ./container-image-api
    container_name: python-image-api
    depends_on:
      - mongodb
      - selenium-chrome
    networks:
      - airflow_app-network
  
networks:
  airflow_app-network:
    external: true

volumes:
  shared_volume: